version: '3'
services:
  app:
    container_name: wp-exporter
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "PYTHONUNBUFFERED=1"
    env_file:
      - .env
    volumes:
      - .:/app